# Site settings
# in the templates available like {{ site.myvariable }}.
title: сайт художника, картины, галерея
email: mikitenkovitya@gmail.com
brand: Виктор Микитенко
headline: Художник, Архитектор
description: > # this means to ignore newlines until "baseurl:"
  Сайт художника Виктора Микитенко, картины, галерея, живопись и архитектура
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mikitenko.org.ua" # the base hostname & protocol for your site
copyright: 2016-2018 Виктор Микитенко

# Build settings
markdown: kramdown

# Account ids
snapwidget: 270863

# Contacts
email: mikitenkovitya@gmail.com
phone: +38 093 959-69-57

# Tracking
googleAnalitycsID: UA-83933844-1

