# Site settings
# in the templates available like {{ site.myvariable }}.
title: сайт художника, картины, галерея
email: your-email@domain.com
brand: Виктор Микитенко
headline: Художник, Архитектор
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Виктор Микитенко

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: your.name@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

